[package]
name = "media-archive"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7"
blake3 = "1.5"
prae = "0.8"
reflink-copy = "0.1"
relative-path = "1.9"
thiserror = { workspace = true }
tracing = { workspace = true }
