[package]
name = "media-archive"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.5"
reflink-copy = "0.1"
relative-path = "1.9"
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert_fs = "1.1"
file-id = "0.2"
predicates = "3.1"
